development:
  secret_key_base: <%= ENV['LEIHS_SECRET'].presence || 'secret' %>

test:
  secret_key_base: <%= ENV['LEIHS_SECRET'].presence || 'secret' %>

production:
  secret_key_base: <%= ENV['LEIHS_SECRET'].presence || (Rails.env.production? ? raise('LEIHS_SECRET env not present!') : 'secret' )%>

